name: web deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install package
    - name: deploy tomcat
      run: curl -v -u ${{ secrets.TOMCAT_USER_NAME }}:${{ secrets.TOMCAT_PASS }} -T /home/runner/work/deploy-war-to-tomcat-githubaction/deploy-war-to-tomcat-githubaction/target/spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://43.204.38.31:8080


    
